### PR TITLE
tooltip and diagram fixes

### LINKED ISSUE #342: tooltips for Alpheios toolbar don't display
if the Alpheios toolbar is expanded and placed on the left side of the screen, when you mouse over Help or Definitions or Options, the related tooltip is not displayed

### PR DESCRIPTION
**Pull request by balmas**
fixes #342 and #516

### CODE REVIEW

File: src/lib/controllers/ui-controller.js [hunk 1]
```diff
@@ -1003,7 +1003,7 @@ export default class UIController {
     return this
   }
 
-  newLexicalRequest (targetWord, languageID) {
+  newLexicalRequest (targetWord, languageID, data=null) {
```
Comment (kirlat) [inline src/lib/controllers/ui-controller.js]: Maybe it's better to provide a more descriptive name to indicate what type of data it is? Is it a text selector data?

Comment (balmas) [reply src/lib/controllers/ui-controller.js]: good idea, yes its text selector data. Will fix.
