### PR TITLE
fix #473

### LINKED ISSUE #473: Lookup fails for words that do not belong to current site
tested in Firefox and Chrome, build 3.0.0.29
in the saved wordlist I have a mix of words from different sites. If I double-click on any of the saved words that do not belong to current site, the lookup fails with Lexical query produced no results.
no result for look-up words that do not belog to that site

### PR DESCRIPTION
**Pull request by balmas**
do full query for worditem if it's not fully populated
also making changes for #388 backwards-compatible

### CODE REVIEW

File: src/vue/vuex-modules/data/auth-module.js [hunk 1]
```diff
@@ -12,8 +12,12 @@ export default class AuthModule extends Module {
     this._externalLoginUrl = null
     this._externalLogoutUrl = null
     if (this._auth) {
-      this._externalLoginUrl = this._auth.loginUrl()
-      this._externalLogoutUrl = this._auth.logoutUrl()
+      try {
```
Comment (balmas) [inline src/vue/vuex-modules/data/auth-module.js]: this is just to keep older code auth module implementations from failing until all the code gets in sync. See #388
