### PR TITLE
fix for #703

### LINKED ISSUE #726: ui text fixes
From review with @abrasax 

In options 'Reasources" should be "Resources"
Remove "Show/Hide" from toolbar tooltip text
Remove "as" from lookup language hint

### PR DESCRIPTION
**Pull request by balmas**
lookup from page should use default language (if can't identify)
rather than current language

also fixes #726 and request from @monzug to change Reset All tip in Options from "Applies" to "Apply"

### CODE REVIEW

File: src/lib/controllers/ui-controller.js [hunk 1]
```diff
@@ -1402,8 +1402,8 @@ export default class UIController {
       HTMLSelector conveys page-specific information, such as location of a selection on a page.
       It's probably better to keep them separated in order to follow a more abstract model.
        */
-      let currentLangCode = LanguageModelFactory.getLanguageCodeFromId(this.store.state.app.currentLanguageID)
-      let htmlSelector = new HTMLSelector(event, currentLangCode)
+      let defaultLangCode = this.getDefaultLangCode()
+      let htmlSelector = new HTMLSelector(event, defaultLangCode)
```
Comment (irina060981) [inline src/lib/controllers/ui-controller.js]: It is a good catch!

File: src/vue/components/options.vue [hunk 2]
```diff
@@ -8,7 +8,7 @@
           <div class="alpheios-tab-options-switch--item" :class="{ 'alpheios-active': currentTab === 2 }" @click="currentTab = 2">F<span class="alpheios-tab-options-switch--item__smaller">eature</span></div>
         </alph-tooltip>
         <alph-tooltip :tooltipText="l10n.getText('OPTIONS_TAB_RESOURCE')" tooltipDirection="bottom-left">
-          <div class="alpheios-tab-options-switch--item" :class="{ 'alpheios-active': currentTab === 3 }" @click="currentTab = 3">R<span class="alpheios-tab-options-switch--item__smaller">easource</span></div>
+          <div class="alpheios-tab-options-switch--item" :class="{ 'alpheios-active': currentTab === 3 }" @click="currentTab = 3">R<span class="alpheios-tab-options-switch--item__smaller">esource</span></div>
```
Comment (irina060981) [inline src/vue/components/options.vue]: I am sorry for this mis-spelling!
